from typing import Optional, TYPE_CHECKING
from sqlalchemy import String, Text, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database.base import Base, UUIDMixin, TimestampMixin, SoftDeleteMixin

if TYPE_CHECKING:
    from database.models.research import ResearchSession


class ResearchPlan(Base, UUIDMixin, TimestampMixin, SoftDeleteMixin):
    """
    Research Plan ORM Model generated by the Planner Agent.
    Contains decomposition, subtopics, search queries, and execution steps.
    """
    __tablename__ = "research_plans"

    research_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("research_sessions.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True
    )
    methodology: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    subtopics: Mapped[dict] = mapped_column(JSON, default=list, nullable=False)
    search_queries: Mapped[dict] = mapped_column(JSON, default=list, nullable=False)
    steps: Mapped[dict] = mapped_column(JSON, default=list, nullable=False)
    status: Mapped[str] = mapped_column(String(50), default="planned", nullable=False)

    # Relationships
    research_session: Mapped["ResearchSession"] = relationship(
        "ResearchSession",
        back_populates="plan"
    )

    def __repr__(self) -> str:
        return f"<ResearchPlan(id={self.id}, research_id={self.research_id}, status={self.status})>"
